[package]
edition      = "2021"
name         = "esp32-wave-28"
rust-version = "1.88"
version      = "0.1.0"

[[bin]]
name = "esp32-wave-2-8"
path = "./src/bin/main.rs"

[dependencies]
anyhow = "1.0"
log = "0.4"

embedded-hal = "1.0.0"
esp-idf-sys = { version = "0.36", features = ["binstart"] }
esp-idf-hal = { version = "0.45" }
esp-idf-svc = { version = "0.51", features = ["std"] }

heapless = "0.8"

slint = { version = "=1.17.1", default-features = false, features = ["std", "renderer-software", "libm", "compat-1-2"] }

[build-dependencies]
embuild = "0.33.2"

slint-build = { version = "=1.17.1" }



[profile.dev]
opt-level = "s"
panic = "abort"

[profile.release]
codegen-units = 1
debug = 2
lto = 'fat'
opt-level = 's'
panic = "abort"

[package.metadata.espflash]
partition_table = "partitions.csv"